version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dvf
      POSTGRES_PASSWORD: dvfpass
      POSTGRES_DB: dvfdb
    volumes:
      - dvf_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  dvf_data:
